# Generated by Django 3.2.5 on 2021-07-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_centerstone_certificate_colorofcstone_currency_jewell_loc_metal1_poj_shape1'),
    ]

    operations = [
        migrations.AddField(
            model_name='poj',
            name='stockid',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
