# Generated by Django 3.2.5 on 2021-07-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_alter_poj_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poj',
            name='center_stone',
        ),
        migrations.RemoveField(
            model_name='poj',
            name='cert',
        ),
        migrations.RemoveField(
            model_name='poj',
            name='color_of_center_stone',
        ),
        migrations.RemoveField(
            model_name='poj',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='poj',
            name='jewellery',
        ),
        migrations.RemoveField(
            model_name='poj',
            name='metal',
        ),
        migrations.RemoveField(
            model_name='poj',
            name='olocation',
        ),
        migrations.RemoveField(
            model_name='poj',
            name='shape',
        ),
    ]
