# Generated by Django 3.2.5 on 2021-07-23 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20210724_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='poj',
            name='center_stone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.centerstone'),
        ),
        migrations.AddField(
            model_name='poj',
            name='cert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.certificate'),
        ),
        migrations.AddField(
            model_name='poj',
            name='color_of_center_stone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.colorofcstone'),
        ),
        migrations.AddField(
            model_name='poj',
            name='company_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='firstapp.purchased'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poj',
            name='jewellery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.jewell'),
        ),
        migrations.AddField(
            model_name='poj',
            name='metal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.metal1'),
        ),
        migrations.AddField(
            model_name='poj',
            name='olocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.loc'),
        ),
        migrations.AddField(
            model_name='poj',
            name='shape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.shape1'),
        ),
    ]
