# Generated by Django 3.2 on 2021-07-24 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20210724_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='companyinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('company_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('mobile_no', models.CharField(max_length=20)),
                ('tel_no', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.EmailField(blank=True, max_length=150, null=True)),
                ('pan_no', models.CharField(max_length=20)),
                ('GST_no', models.CharField(max_length=20)),
                ('line_id', models.CharField(blank=True, max_length=20, null=True)),
                ('wechat_id', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.countries')),
            ],
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.RemoveField(
            model_name='poj',
            name='center_stone',
        ),
        migrations.RemoveField(
            model_name='poj',
            name='cert',
        ),
        migrations.RemoveField(
            model_name='poj',
            name='color_of_center_stone',
        ),
        migrations.RemoveField(
            model_name='poj',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='poj',
            name='jewellery',
        ),
        migrations.RemoveField(
            model_name='poj',
            name='metal',
        ),
        migrations.RemoveField(
            model_name='poj',
            name='olocation',
        ),
        migrations.RemoveField(
            model_name='poj',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='purchased',
            name='country',
        ),
        migrations.RemoveField(
            model_name='purchased',
            name='gem',
        ),
        migrations.DeleteModel(
            name='centerstone',
        ),
        migrations.DeleteModel(
            name='certificate',
        ),
        migrations.DeleteModel(
            name='colorofcstone',
        ),
        migrations.DeleteModel(
            name='jewell',
        ),
        migrations.DeleteModel(
            name='loc',
        ),
        migrations.DeleteModel(
            name='metal1',
        ),
        migrations.DeleteModel(
            name='POJ',
        ),
        migrations.DeleteModel(
            name='purchased',
        ),
        migrations.DeleteModel(
            name='shape1',
        ),
    ]
