# Generated by Django 3.2.5 on 2021-07-24 11:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_centerstone_certificate_colorofcstone_currency_jewell_loc_metal1_shape1'),
    ]

    operations = [
        migrations.CreateModel(
            name='POJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('stockid', models.CharField(max_length=30)),
                ('grosswt', models.BigIntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('pieces', models.BigIntegerField()),
                ('amount', models.BigIntegerField()),
                ('discount', models.IntegerField()),
                ('discount_amount', models.BigIntegerField()),
                ('total_val', models.BigIntegerField()),
                ('tag_price', models.BigIntegerField()),
                ('rate', models.IntegerField()),
                ('center_stone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.centerstone')),
                ('cert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.certificate')),
                ('color_of_center_stone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.colorofcstone')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.companyinfo')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.currency')),
                ('jewellery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.jewell')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.loc')),
                ('metal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.metal1')),
                ('shape', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.shape1')),
            ],
        ),
    ]
