# Generated by Django 3.2.5 on 2021-07-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_auto_20210727_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poj',
            name='total_val',
        ),
    ]
