# Generated by Django 3.2.5 on 2021-07-27 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_auto_20210727_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poj',
            name='cert',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='firstapp.certificate'),
            preserve_default=False,
        ),
    ]
