# Generated by Django 3.2.5 on 2021-07-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_alter_poj_cert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poj',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
