# Generated by Django 3.2 on 2021-07-28 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0017_auto_20210728_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='poj',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='firstapp.currency'),
            preserve_default=False,
        ),
    ]
