# Generated by Django 3.2.5 on 2021-07-28 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0018_poj_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poj',
            name='center_stone',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='firstapp.centerstone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poj',
            name='cert',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='firstapp.certificate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poj',
            name='jewellery',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='firstapp.jewell'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poj',
            name='location',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='firstapp.loc'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poj',
            name='metal',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='firstapp.metal1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poj',
            name='shape',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='firstapp.shape1'),
            preserve_default=False,
        ),
    ]
