# Generated by Django 3.2.5 on 2021-07-28 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0020_alter_poj_color_of_center_stone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poj',
            name='center_stone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.centerstone'),
        ),
    ]
