# Generated by Django 3.2.5 on 2021-07-28 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0021_alter_poj_center_stone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poj',
            name='cert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.certificate'),
        ),
    ]
