# Generated by Django 3.2.5 on 2021-07-28 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0024_auto_20210728_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poj',
            name='currency',
        ),
    ]
